name: lineal-amp
description: |
  this is a test amp to see how to approach amp development

author: luis
specification_version: 1.0
prototype_version: 1.0
date: "2023-10-12"

runtimes:
  - editor: Workbench
    kernel: Python 3.9
    edition: Standard

tasks:
  - type: run_session
    name: run a test
    script: experiments/test.py
    short_summary: test args in file 
    long_summary: checking that the task runs
    kernel: python3
    cpu: 1
    memory: 2

  - type: run_session
    name: install dependencies
    script: 01-install-dep/install_dep.py
    short_summary: install dependencies
    long_summary: install dependencies for the current project 
    kernel: python3
    cpu: 2
    memory: 4

  - type: run_session
    name: train model and log params
    script: experiments/experiment_mlflow.py
    short_summary: train lineal model 
    long_summary: first training and creation of experiment for tracking
    kernel: python3
    cpu: 2
    memory: 4
  
  - type: run_session
    name: dowload run artifacts(models)
    script: models/get_mlflow_run_query_based.py
    short_summary: get model from run 
    long_summary: get model from run base on some metric
    kernel: python3
    cpu: 2
    memory: 4 